bin/build.sh, recipes/headers/Dockerfile, recipes/headers/run.sh
This adds a recipe that downloads a copy of the headers to be included in the Unofficial Builds releases and changes the RELEASE_URLBASE to point to that copy.
The node-gyp changes in https://github.com/nodejs/node-gyp/pull/1875 require this. Windows ARM64 releases need to download `node.lib` from this server. Changing node-gyp to get `node.lib` from here and the headers from the main server doesn't make much sense to me. This approach makes it more consistent, at the expense of having to duplicate the headers files.
@rvagg can you take a look? I haven't tested this. I plan to land this, let docker update and then fix anything that needs fixing. But I can test the changes in the server and update this PR if you prefer. In any case, I'll run the new recipe for v12.8.0 which I'm using to …
=> change RELEASE_URLBASE to the Unofficial Builds server

bin/build.sh
v12.11.0 was not published because of a failure building x86. Until that is fixed it is blocking other recipes and promotion of assets. This PR changes `build.sh` to keep building other recipes when one fails.
This was not tested, I will fix any issue if we agree this is the way to move forward.
cc @rvagg
=> ignore failures building all recipes but fetch-source

recipes/armv6l/Dockerfile
Adding '-y' prevents the following prompt from blocking Docker's progress.
```
More info: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test                                                                                                                   
Press [ENTER] to continue or ctrl-c to cancel adding it  
```
=> Add -y flag to add-apt-repository

recipes/armv6l/Dockerfile
Ref: https://github.com/nodejs/unofficial-builds/pull/29
=> fix: python2 is just python on xenial

README.md
=> Note that libstdc++ is a required package on Alpine Linux

bin/build.sh, recipes/armv6l/Dockerfile
Add the renamed `armv6l-pre16` recipe to the explicit recipe list to build.
Add missing dependency (`python3-distutils`) for the new `armv6l` recipe to fix 
```
ModuleNotFoundError: No module named 'distutils.spawn'
```
error. FWIW in https://github.com/nodejs/build/blob/master/ansible/roles/docker/templates/ubuntu1804_arm_cross.Dockerfile.j2 `python3-distutils` is installed as a dependency of `python3-pip` -- we do not need to install pip on the unofficial build Docker image as we're not running tap2junit here.
Refs: https://github.com/nodejs/unofficial-builds/pull/33
=> fixup armv6l recipes

recipes/fetch-source/Dockerfile, recipes/fetch-source/run.sh, recipes/headers/Dockerfile, recipes/headers/run.sh
SKS no longer publishes DNS. Same approach from docker-node
Fixes https://github.com/nodejs/unofficial-builds/issues/37
=> chore: Use openpgp/ubuntu keyservers

recipes/x64-pointer-compression/Dockerfile, recipes/x64-pointer-compression/cloudlinux.repo, recipes/x64-pointer-compression/run.sh, recipes/x64-usdt/Dockerfile, recipes/x64-usdt/cloudlinux.repo, recipes/x64-usdt/run.sh, recipes/x86/Dockerfile, recipes/x86/cloudlinux.repo, recipes/x86/run.sh
Node.js 16 requires gcc/g++ 8.3 or later.
V8 9.2 included in Node.js 16.6.0 fails to compile with gcc/g++ 8.2.1:
https://unofficial-builds.nodejs.org/logs/202107292303-v16.6.0/x64-usdt.log
<details>
```
../deps/v8/src/builtins/builtins-call-gen.cc: In instantiation of 'void v8::internal::CallOrConstructBuiltinsAssembler::CallReceiver(v8::internal::Builtins::Name, v8::internal::TNode<v8::internal::Int32T>, v8::internal::TNode<v8::internal::UintPtrT>, v8::base::Optional<v8::internal::TNode<v8::internal::Object> >) [with Descriptor = v8::internal::CallTrampoline_BaselineDescriptor]':
../deps/v8/src/builtins/builtins-call-gen.cc:81:42:   required from here
../deps/v8/src/builtins/builtins-call-gen.cc:491:14: error: passing 'const v8::base::Optional<v8::internal::TNode<v8::internal::Object> >' …
```
=> Update compiler for Node.js 16

bin/prepare-images.sh, recipes/armv6l-pre16/Dockerfile, recipes/armv6l/Dockerfile, recipes/fetch-source/Dockerfile, recipes/headers/Dockerfile, recipes/musl/Dockerfile, recipes/x64-pointer-compression/Dockerfile, recipes/x64-usdt/Dockerfile, recipes/x86/Dockerfile
Allow the user ID and group IDs to be changed when preparing the images for running/testing on systems where the host is running under a user with a user ID other than 1000.
I'm testing out some changes and the system I'm using is shared so my user id is not 1000. This PR allows me to only have to modify one place (`bin/prepare-images.sh`) to change the user id so I can successfully mount the shared directories from the host.
=> Allow setting user and group ID

recipes/fetch-source/Dockerfile, recipes/fetch-source/run.sh, recipes/headers/Dockerfile, recipes/headers/run.sh, recipes/musl/Dockerfile
Since 3.9 hit EOL last year, I figure I'd update the base https://alpinelinux.org/releases/. Alternate would be just to bump to 3.12, since it's the oldest supported version
- Use latest alpine for headers/fetch jobs
- Update docker-node keys for branch rename
- use latest Alpine for Musl builder image
=> chore: update Apline versions

README.md, bin/build.sh, recipes/riscv64/Dockerfile, recipes/riscv64/run.sh, recipes/riscv64/should-build.sh
Configuration to allow building for RISC-V as an unofficial build platform.
Since this is my first contribution to here and I don't have access to the box used for cross-compilation I cannot verify for certain that it will work properly, but the setup seems adequate for building the latest versions for RISC-V.
(If `run.sh` isn't the right place to add the configure arguments, let me know)
Should e enough to satisfy the requirements to [move RISC-V to experimental](https://github.com/nodejs/build/issues/2876)
Signed-off-by: Stewart X Addison <sxa@redhat.com>
=> Add recipe definition for building on riscv64

recipes/riscv64/Dockerfile
Fixes https://github.com/nodejs/unofficial-builds/issues/79 (Name resolution changed a few weeks ago for the server that the toolchain is being pulled from).
May be superceded by https://github.com/nodejs/unofficial-builds/pull/75 but this is a quick fix to stop things breaking an allow us to get builds out as they are currently built
=> update link to riscv64 toolchain

recipes/x64-glibc-217/cloudlinux.repo
The `x64-glibc-217` recipe is only built for Node.js 18+ and hence `devtoolset-8` is not needed here (only needed for versions <16)
=> Remove unused yum repo from x64-glibc-217 recipe

recipes/x64-glibc-217/Dockerfile, recipes/x64-glibc-217/cloudlinux.repo
This PR should make the `x64-glibc-217` recipe a little simpler by removing the custom yum repo used to install `devtoolset-9`. Instead we can get `devtoolset-9` from installing `centos-release-scl-rh`.
I've also added a `ulimit -n 1024` before running `yum` because of this known issue on centos 7: https://stackoverflow.com/questions/74345206/centos-7-docker-yum-installation-gets-stuck
I haven't personally run into this bug on centos 7, but it seems to be a good idea to add it to make the install more stable.
=> Remove custom yum repo in favor for centos-release-scl-rh

recipes/fetch-source/run.sh
This PR is in response to the fetch-source script failing on multiple occasions in the past. https://github.com/nodejs/unofficial-builds/issues/87, https://github.com/nodejs/unofficial-builds/issues/81, https://github.com/nodejs/unofficial-builds/issues/86
If the request fails, the curl command is repeated a total of 6 times (10 second sleep time), which equates to a minute total wait time. I think that should be enough time for any potential cache issues to resolve.
=> fix: retry fetch-source curl request

README.md, bin/build.sh, recipes/loong64/Dockerfile, recipes/loong64/run.sh, recipes/loong64/should-build.sh
Configuration to allow building for LoongArch as an unofficial build platform.
Since this is my first contribution to here and I don't have access to the box used for cross-compilation I cannot verify for certain that it will work properly, but the setup seems adequate for building the latest versions for LoongArcch.
(If there are problems with the "loong64 nodejs" build, please let me know, thank you very much)
Cheers~
=> Add recipe definition for building on loong64

recipes/loong64/should-build.sh
loong64: The v18.x branch supports loong64 builds from v18.18.0 (--openssl-no-asm)
The loong64 platform "--openssl-no-asm" supports patch:
https://github.com/nodejs/node/commit/f4617a4f81
https://github.com/nodejs/node/commit/3be53358bc
=> loong64: v18.x branch supports loong64 builds from v18.18.0 

README.md, bin/local_build.sh, recipes/fetch-source/Dockerfile
About time this got done, mainly useful for people contributing new recipes, so they can actually test them locally (and we can too).
=> feat: add local_build.sh script and instructions for local/dev use

recipes/fetch-source/Dockerfile
addresses a problem where gnupg creates a lockfile in the directory which causes problems when trying to invoke it later on during a run of fetch-source
Ref: https://github.com/nodejs/unofficial-builds/pull/109
Closes: https://github.com/nodejs/unofficial-builds/pull/109
=> fix: create ~/.gnupg prior to invoking gnupg

README.md, bin/_config.sh, bin/build.sh, bin/local_build.sh, bin/prepare-images.sh
I'm doing a bit of a security balancing act here. I've enabled auto-releases on https://github.com/nodejs/nodejs-dist-indexer, because it's just so much simpler and more efficient to get changes shipped. _But_ we use `npx` to run it here, so while it's easier to get releases out, it opens a novel vector for getting privileged(-enough) access on the unofficial-builds server to mess with binaries.
So this change puts the burden on the person adding a new recipe to get dist-indexer updated and put the new version number into the config here.
=> feat: add explicit versioning for nodejs-dist-indexer

recipes/x64-glibc-217/run.sh
nodejs sources were updated with some glibc 2.25+ functionality around expecting/detecting sys/random.h and getrandom()
This target specifically is meant for lesser glibc versions, thus we specifically disable the new expectations
=> Update run.sh to exclude sys/random.h for this target

recipes/armv6l/run.sh, recipes/x64-glibc-217/run.sh, recipes/x64-pointer-compression/run.sh, recipes/x86/run.sh
Builds succeed:
❯  ls -al ~/src/github/staging/release/v20.12.1|grep -v musl|grep -v xz
total 695032
drwxr-xr-x  12 scosol  staff       384 Apr  5 12:35 .
drwxr-xr-x   4 scosol  staff       128 Apr  3 11:31 ..
-rw-------@  1 scosol  staff  43014257 Apr  5 12:35 node-v20.12.1-linux-armv6l.tar.gz
-rw-------@  1 scosol  staff  46947672 Apr  3 12:48 node-v20.12.1-linux-x64-glibc-217.tar.gz
-rw-------@  1 scosol  staff  47016182 Apr  4 12:28 node-v20.12.1-linux-x64-pointer-compression.tar.gz
-rw-------@  1 scosol  staff  45960624 Apr  4 21:58 node-v20.12.1-linux-x86.tar.gz
=> Adding SYS_RANDOM and GET_RANDOM fixes to x86, x64-pointer-compression, armv6l

bin/build.sh, bin/local_build.sh
Quick attempt at fixing this problem: https://unofficial-builds.nodejs.org/logs/202404060129-v20.12.0/armv6l.log
=> fix: remove quotes from -v mounts

bin/build.sh
another overzealous quote that is avoiding wildcard expansion leading to this error:
```
+ mv '/home/nodejs/staging/release/v20.12.0/node-v*' /home/nodejs/download/release/v20.12.0
mv: cannot stat '/home/nodejs/staging/release/v20.12.0/node-v*': No such file or directory
```
in https://unofficial-builds.nodejs.org/logs/202404060140-v20.12.0/build.log
even though the files are there
/cc @matthewkeil
=> fix: unquote wildcard for staging file move

recipes/x64-usdt/run.sh, recipes/x64-usdt/should-build.sh
Node19+ removed dtrace support, thus there is no point/ability to build this target for these versions.
=> Adding no-build logic for x64-usdt target if node version > 18

README.md
This little change in the README.md helps and closes https://github.com/nodejs/unofficial-builds/issues/123 due a rare error like `ccache: error: Could not find compiler "g++" in PATH`  .. instructions was improved for non familiar with nodejs build process
Aditional, apparently not all recipes compile in all flavors, I have noticed, for example, that in 16.x.y they only compile some while in 20.x.y they compile almost all of them. i noted this also in the alredy released tarball, by example https://unofficial-builds.nodejs.org/download/release/v20.11.1/ already have almost all recipes .. but for https://unofficial-builds.nodejs.org/download/release/v16.20.2/ i noted there is not x64-glibc-217 recipe released..
=> expands information for local compilations, clarify not all recipes builds

recipes/musl/Dockerfile
- Still supported
- Used by the official Node.js Docker images
Closes: https://github.com/nodejs/unofficial-builds/issues/103
=> chore: update Alpine to 3.18

bin/_config.sh
Ref: https://github.com/nodejs/unofficial-builds/issues/138
haven't figured out why this is demanding so much space yet, but it might need a resize of the root device which I'm not looking forward to pulling off, either that or putting docker var onto a separate device
=> fix: move debug build to last since it's failing atm

bin/local_build.sh
For a fresh local build, the script expects the build queue to be in a location matching its location on the PROD server (relative to the bin dir), which doesn't exist unless created by the user.
Instead, we will create this structure in the local_build.sh file so that the script works immediately.
=> Adding instantiation of local var/build_queue

recipes/x86/should-build.sh
x86 is no longer supported and x86 builds fail in version 22. Disabling the build to prevent a the failing buikld to abort other recipes.
=> Disable x86 builds for version 22 and higher

recipes/armv6l/should-build.sh
Since Node 16 isn't supported anyway, I swapped the check to match #142 
v22 errors can be seen in https://unofficial-builds.nodejs.org/logs/202404242143-v22.0.0/armv6l.log in case someone wants to try and fix it later
=> ci: Disable armv6l on Node 22+

recipes/musl/Dockerfile
This is necessary to compile V8 with C++20 support.
Refs: https://github.com/nodejs/node/pull/45427
=> chore: update Alpine to 3.19

recipes/x64-glibc-217/Dockerfile, recipes/x64-pointer-compression/Dockerfile, recipes/x64-usdt/Dockerfile, recipes/x86/Dockerfile
Fixes #147.
All the centos:7 builds are failing because [the mirrorlist for centos repos has removed CentOS 7](https://support.cpanel.net/hc/en-us/articles/24571139547415-Could-not-retrieve-mirrorlist-http-mirrorlist-centos-org-on-CentOS-7).  This fixes this by modifying the yum repo config files so we fetch repos from valut.centos.org instead of from the mirrorlist URLs.
Tried this out with `x64-glibc-217` and made sure it built successfully.  I also tried `x64-pointer-compression` and stopped it before it completed, but made sure it got into the compilation phase (it won't get anywhere near that far without this fix).
=> fix: Do not use mirrorlist for centos:7 builds.

recipes/x64-glibc-217/Dockerfile, recipes/x64-glibc-217/run.sh
1. Upgrade GCC version to 12 and Python version to 3.8
2. Backport the patch from https://github.com/c-ares/c-ares/issues/850
=> fix: x64-glibc-217 build failed for v22.7.0

recipes/musl/Dockerfile
not available in alpine:3.19, failing to build
nothing new is being deployed because this is failing: https://unofficial-builds.nodejs.org/logs/github-webhook.log
=> fix: remove python2 from musl build

recipes/loong64/Dockerfile
simdjson and simdutf have completed LSX and LASX support 
Binutils version 2.41 and GCC version 14.1.0 support LSX and LASX instruction sets
Reference:
https://github.com/loongson/build-tools/wiki#binutils-related-support
https://github.com/loongson/build-tools/wiki#gcc-related-support
Updated cross-toolchain to support LSX/LASX instruction sets
=> upgrade the LoongArch64 architecture cross-compilation toolchain

recipes/loong64/Dockerfile, recipes/loong64/run.sh, recipes/loong64/should-build.sh
The build of the LoongArch64 architecture has been stopped for a while, and the problem affecting the build has been fixed.
I tested the _**v18.x**~**24.x**_ versions in the new environment
1. Migrated build environment to `ubuntu:24.04` base image  
2. Adopted `gcc-14-loongarch64-linux-gnu` and `g++-14-loongarch64-linux-gnu` toolchains for LoongArch64 architecture builds  
3. Executed comprehensive builds using `./bin/local_build.sh -r loong64 -v $version` across Node.js versions 18.x to 24.x
Verified Build Success:
|   | Version Range | Build Status | Notes|
|-------|-------|-------|----------|
| 18.x | v18.18.0 - v18.20.6 |Successful |  v18.20.7~ requires simdutf ≥6.2.1(https://github.com/nodejs/node/issues/56280#issuecomment-2709233410) |
| 20.x | v20.10.0 - v20.19.2(current)  | …
=> build: use Ubuntu 24.04 and gcc-14 for LoongArch64 builds

recipes/x64-glibc-217/should-build.sh
Python version problems
Ref: https://unofficial-builds.nodejs.org/logs/202507160208-v24.4.1/x64-glibc-217.log
Ref: https://github.com/nodejs/unofficial-builds/issues/176
=> chore: stop building x64-glibc-217 on v24 until fixed

recipes/loong64/should-build.sh
Ref: https://unofficial-builds.nodejs.org/logs/202507290214-v24.4.1/loong64.log
Ref: https://github.com/nodejs/unofficial-builds/issues/176
=> chore: disable loong64 for v24 due to outdated python

recipes/x64-debug/should-build.sh
Ref: https://unofficial-builds.nodejs.org/logs/202507290341-v24.4.1/x64-debug.log
C++ version problem? Needs someone to look and fix the recipe. Disabling for now.
=> chore: disable x64-debug
